# Lab 06: Softmax function -- demo

In [1]:
import torch
import torch.nn.functional as F

### Make a vector

In [3]:
x=torch.Tensor([ -2 , -0.5 , 2.0 , 1.5 ])
print(x)
print(x.size())

tensor([-2.0000, -0.5000,  2.0000,  1.5000])
torch.Size([4])


### Feed it to the softmax

In [6]:
p=F.softmax(x , dim=0)
print(p)
print(p.size())

tensor([0.0107, 0.0481, 0.5858, 0.3553])
torch.Size([4])


### Check that it sums to one

In [4]:
print(  p.sum()  )

tensor(1.)


### Make a matrix a matrix

In [5]:
A=torch.Tensor( [ [ -2 , -0.5 , 2.0 , 1.5 ] , [ -2 , -0.5 , 7.0 , 1.5 ] ])
print(A)

tensor([[-2.0000, -0.5000,  2.0000,  1.5000],
        [-2.0000, -0.5000,  7.0000,  1.5000]])


### Take the softmax over the rows (dim=1)

In [6]:
p = F.softmax(A , dim=1)
print(p)

tensor([[0.0107, 0.0481, 0.5858, 0.3553],
        [0.0001, 0.0006, 0.9953, 0.0041]])


### Take the softmax over the columns (dim=0)

In [7]:
p = F.softmax(A , dim=0)
print(p)

tensor([[0.5000, 0.5000, 0.0067, 0.5000],
        [0.5000, 0.5000, 0.9933, 0.5000]])
