# Lab 07: Vanilla neural networks -- exercise

# Creating a one-layer network

In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Make a class for a one layer network. Let's call the layer "mylayer". And let's give it a bias.

In [38]:
class one_layer_net(nn.Module):

    def __init__(self,  input_size, output_size  ):
        super(one_layer_net , self).__init__()
        
        # complete here
        self.layer1 = nn.Linear(input_size, output_size, bias=True)
        
    def forward(self, x):
        
        x = self.layer1(x)# complete here
        p = F.softmax(x, dim=0)# complete here
        
        return p

### Create an instance of a one layer net that take input of size 2 and return output of size 2

In [39]:
net= one_layer_net(2,2)# complete here
print(net)

one_layer_net(
  (layer1): Linear(in_features=2, out_features=2, bias=True)
)


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to the network. What is the output probability? Check that it sums to one.

In [40]:
x= torch.ones(2)# complete here
print(x)

p = net.forward(x)  # complete here
print(p)

print(p.sum() )

tensor([1., 1.])
tensor([0.8473, 0.1527], grad_fn=<SoftmaxBackward>)
tensor(1.0000, grad_fn=<SumBackward0>)


### Print the weights as well as the bias of the unique layer of this network. Be careful to use the correct name for this unique layer 

In [41]:
print(net.layer1.weight) # complete here)
print(net.layer1.bias) # complete here)

Parameter containing:
tensor([[-0.5051,  0.6557],
        [-0.4907, -0.1788]], requires_grad=True)
Parameter containing:
tensor([ 0.3830, -0.5105], requires_grad=True)


### Change the internal parameters of your network so that the weights are now equal to $
W=\begin{bmatrix}
1&2 \\ 3&4 
\end{bmatrix}
$ and the bias is equal to  $
b=\begin{bmatrix}
1 \\ 1 
\end{bmatrix}
$ 

In [44]:
# CHANGE THE WEIGHTS
net.layer1.weight[0,0] = 1 # complete here
net.layer1.weight[0,1] = 2 # complete here
net.layer1.weight[1,0] = 3 # complete here
net.layer1.weight[1,1] = 4 # complete here

# CHANGE THE BIAS
net.layer1.bias[0] = 1 # complete here
net.layer1.bias[1] = 1 # complete here

# print(net.mylayer.weight)
# print(net.mylayer.bias)
print(net.layer1.weight)
print(net.layer1.bias)

Parameter containing:
tensor([[1., 2.],
        [3., 4.]], grad_fn=<CopySlices>)
Parameter containing:
tensor([1., 1.], grad_fn=<CopySlices>)


### Feed the vector x to your network with updated parameters. What is the output? (you should get p= [2% 98%])

In [45]:
p= net(x) # complete here
print(p)

tensor([0.0180, 0.9820], grad_fn=<SoftmaxBackward>)
