# Lab 07: Vanilla neural networks -- solution

# Creating a one-layer network

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Make a class for a one layer network. Let's call the layer "mylayer". And let's give it a bias.

In [2]:
class one_layer_net(nn.Module):

    def __init__(self,  input_size, output_size  ):
        super(one_layer_net , self).__init__()
        
        self.mylayer=nn.Linear(input_size,output_size, bias=True)
        
        
    def forward(self, x):
        
        x = self.mylayer(x)
        p = F.softmax(x,dim=0)
        
        return p

### Create an instance of a one layer net that take input of size 2 and return output of size 2

In [3]:
net= one_layer_net(2,2)
print(net)

one_layer_net(
  (mylayer): Linear(in_features=2, out_features=2, bias=True)
)


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to the network. What is the output probability?

In [4]:
x= torch.Tensor([1,1])
print(x)
p =  net(x)
print(p)
print(p.sum() )

tensor([1., 1.])
tensor([0.5447, 0.4553], grad_fn=<SoftmaxBackward>)
tensor(1., grad_fn=<SumBackward0>)


### Print the weights as well as the bias of the unique layer of this network. Be careful to use the correct name for this unique layer 

In [5]:
print(net.mylayer.weight)
print(net.mylayer.bias)

Parameter containing:
tensor([[-0.3148,  0.5843],
        [ 0.3549, -0.1694]], requires_grad=True)
Parameter containing:
tensor([0.3936, 0.2985], requires_grad=True)


### Change the internal parameters of your network so that the weights are now equal to $
W=\begin{bmatrix}
1&2 \\ 3&4 
\end{bmatrix}
$ and the bias is equal to  $
b=\begin{bmatrix}
1 \\ 1 
\end{bmatrix}
$ 

In [6]:
net.mylayer.weight[0,0]=1
net.mylayer.weight[0,1]=2
net.mylayer.weight[1,0]=3
net.mylayer.weight[1,1]=4

net.mylayer.bias[0]=1
net.mylayer.bias[1]=1

print(net.mylayer.weight)
print(net.mylayer.bias)

Parameter containing:
tensor([[1., 2.],
        [3., 4.]], grad_fn=<CopySlices>)
Parameter containing:
tensor([1., 1.], grad_fn=<CopySlices>)


### Feed the vector x to your network with updated parameters. What is the output? (you should get p= [2% 98%])

In [7]:
p=net(x)
print(p)

tensor([0.0180, 0.9820], grad_fn=<SoftmaxBackward>)
