In [16]:
import numpy as np

In [1]:
class Complex:
    
    #constructor
    def __init__(self, real, imagine):
        self.re = real
        self.im= imagine

HELLO


In [2]:
pwd

'/home/wesley/CE7454_2018/CE7454_2018/codes'

In [3]:
cd lab01_python

/home/wesley/CE7454_2018/CE7454_2018/codes/lab01_python


In [4]:

n = 10**7
x = np.linspace(0,1,n)
y = np.linspace(0,2,n)

In [13]:
x.T

array([0.0000000e+00, 1.0000001e-07, 2.0000002e-07, ..., 9.9999980e-01,
       9.9999990e-01, 1.0000000e+00])

In [10]:
y.shape

(10000000,)

In [14]:
x.T.dot(y)

6666667.000000033

In [15]:
x.T@y

6666667.000000033

In [17]:
import torch

In [18]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


In [23]:
x.shape

torch.Size([3])

In [24]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)


tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


In [25]:
A.shape

torch.Size([2, 2])

In [27]:
torch.zeros(1,2)

tensor([[0., 0.]])

In [28]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)

tensor([[0.9731, 0.6082],
        [0.5584, 0.9708]])
