# Lab 17: GPU demo

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Set the device variable to be either cuda or cpu

In [3]:
device = torch.device("cuda")

#device = torch.device("cpu")

print(device)

cuda


### Make a random tensor (by default the tensor is created on the CPU)

In [4]:
x=torch.rand(3,3)

print(x)

tensor([[0.7986, 0.7116, 0.2708],
        [0.2068, 0.8142, 0.9892],
        [0.1417, 0.8848, 0.8121]])


### Send the tensor to the device (which is going to be be the GPU if the device was set to be the GPU -- otherwise it will remain on the CPU)

In [5]:
x=x.to(device)

print(x)

tensor([[0.7986, 0.7116, 0.2708],
        [0.2068, 0.8142, 0.9892],
        [0.1417, 0.8848, 0.8121]], device='cuda:0')


### Make a one layer net class

In [6]:
class one_layer_net(nn.Module):

    def __init__(self, input_size, output_size):
        super(one_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, output_size , bias=False)
        
    def forward(self, x):
        scores = self.layer1(x)
        return scores

### Build the net

In [7]:
net=one_layer_net(5,2)

### Send all the weights of the network to the GPU

In [8]:
net = net.to(device)

### Ckeck that the matrix is indeed on the GPU

In [9]:
print(net.layer1.weight)

Parameter containing:
tensor([[ 0.2327, -0.1627, -0.3238, -0.3470, -0.3678],
        [ 0.1391,  0.1356, -0.1820, -0.3775, -0.3469]],
       device='cuda:0', requires_grad=True)
